# Generated by Django 5.2 on 2025-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_pet_description_pet_gender_pet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
