# Generated by Django 5.2 on 2025-05-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_cart_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('totalbill', models.IntegerField()),
                ('petid', models.ForeignKey(db_column='petid', on_delete=django.db.models.deletion.CASCADE, to='petapp.pet')),
                ('user_id', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
